### ISSUE TITLE
Cannot build in Windows 10

### ISSUE THREAD

**Issue by lingzhixu6** [kingsoft-wps/KSAI-Toolkits#1]
I have followed all the steps described in README.md but still cannot build successfully.
Here is a screenshot of my error message.
![图片](https://user-images.githubusercontent.com/45755579/126960739-915c7c84-5cfb-4575-96f3-5043d6afcc9d.png)

Any help is appreciated!

**Comment by kingsoft-wps** [comment]
> I have followed all the steps described in README.md but still cannot build successfully.
> Here is a screenshot of my error message.
> ![图片](https://user-images.githubusercontent.com/45755579/126960739-915c7c84-5cfb-4575-96f3-5043d6afcc9d.png)
> 
> Any help is appreciated!
maybe your cmake version too low, please refer to 
![image](https://user-images.githubusercontent.com/82071640/127451700-98d4d7d5-fbcd-4680-b861-e083cbc93386.png)
