### ISSUE TITLE
build on ubuntu failed

### ISSUE THREAD

**Issue by kaierlong** [kingsoft-wps/KSAI-Toolkits#4]
os version: Ubuntu 16.04.7 LTS
cmake version: 3.20.0
gcc version: 5.4.0

I use bulid_linux.sh to bulid, but failed.

=== logs ===

CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project Directory: /home/xxx/codes/KSAI-Toolkits
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/codes/KSAI-Toolkits/output/linux
[  8%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/base/ks_common_op.cpp.o
[ 16%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/base/ks_inference_base.cpp.o
[ 25%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/base/ks_loader_op.cpp.o
[ 33%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/OCR/ks_ocr_det.cpp.o
[ 41%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/OCR/ks_ocr_cls.cpp.o
[ 50%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/OCR/ks_ocr_recog.cpp.o
[ 58%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/OCR/ks_ocr_utility.cpp.o
[ 66%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/OCR/ks_ocr.cpp.o
[ 75%] Building CXX object src/CMakeFiles/KSAI-Toolkits.dir/__/3rdparty/clipper/clipper.cpp.o
[ 83%] Linking CXX shared library ../lib/libKSAI-Toolkits.so
[ 83%] Built target KSAI-Toolkits
[ 91%] Building CXX object test/CMakeFiles/KSAI_Toolkits_demo.dir/test_ocr.cpp.o
[100%] Linking CXX executable ../bin/KSAI_Toolkits_demo
//home/xxx/codes/KSAI-Toolkits/3rdparty/libs/linux_x86_64/ksai-lite/libtensorflow-lite.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
//home/xxx/codes/KSAI-Toolkits/3rdparty/libs/linux_x86_64/ksai-lite/libtensorflow-lite.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
//home/xxx/codes/KSAI-Toolkits/3rdparty/libs/linux_x86_64/ksai-lite/libtensorflow-lite.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
collect2: error: ld returned 1 exit status
test/CMakeFiles/KSAI_Toolkits_demo.dir/build.make:98: recipe for target 'bin/KSAI_Toolkits_demo' failed
make[2]: *** [bin/KSAI_Toolkits_demo] Error 1
CMakeFiles/Makefile2:141: recipe for target 'test/CMakeFiles/KSAI_Toolkits_demo.dir/all' failed
make[1]: *** [test/CMakeFiles/KSAI_Toolkits_demo.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

=== logs ===

Any help for this error？Thank you！

**Comment by kingsoft-wps** [comment]
hi，maybe the version of your libstdc++.so.6 is too low, upgrade this lib; this blog (https://blog.csdn.net/SweetSeven_/article/details/110186738) can help you

**Comment by kaierlong** [comment]
@kingsoft-wps 
Thank you. 
After I link the libstdc++.so.6.0.22 to libstdc++.so.6.  There is no error now. And The test is ok.

**Comment by kingsoft-wps** [comment]
ok
